apiVersion: apps/v1
kind: Deployment
metadata:
  name: coolapp-v1
  labels:
    app: coolapp
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: coolapp
      version: v1
  template:
    metadata:
      labels:
        app: coolapp
        version: v1
    spec:
      containers:
      - name: coolapp
        image: coolapp:latest
        imagePullPolicy: Never
        command: ["/app/main"]
        args: ["v1"]
        ports:
        - containerPort: 8080
